### ISSUE TITLE
Load untransformed geometries with cityjson.load()

### ISSUE THREAD

**Issue by LaurensJN** [cityjson/cjio#111]
I updated to CJIO 0.6.10 and now, instead of getting the untransformed (integer) vertex list when calling the boundaries of a geometry, it returns the actual (float) coordinates of the geometry. See:

```python
from cjio import cityjson

citymodel = cityjson.load("example/3dbag_v210908.json")
for obj_id, obj in citymodel.get_cityobjects().items():
    boundaries = obj.geometry[0].boundaries
```

I used to be able to build a dict from the integer vertex list and therefore reuse the same vertex if it is in multiple faces / objects. Now this is not possible anymore because of the float values. Is there any other way to get the vertex id (or untransformed coordinates) instead of the vertex coordinates here?

**Comment by balazsdukai** [comment]
Yes, with `cityjson.load("example/3dbag_v210908.json", transform=False)`
