### ISSUE TITLE
cjio does not provide the extra 'validate'

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/cjio#118]
On commit fdc6e22 

The readme says that the extra packages required for validation can be installed with the extra 'validate', like `pip install cjio [validate]`, but setup.py does not define this extra.
I'm not sure how you want to do this @hugoledoux , so I just opened this issue as a reminder.

**Comment by hugoledoux** [comment]
I'll add it to the list once I have a github action for [cjvalpy](https://github.com/cityjson/cjvalpy) to create the wheels for diff python versions + OSes.

**Comment by hugoledoux** [comment]
Fixed in 130bce14b2edadf6d67f51181b1858fbd252c2af
