### ISSUE TITLE
subset individual CityObjects with their IDs

### ISSUE THREAD

**Issue by Saji70** [cityjson/cjio#122]
Dear cjio Team

Would you please give me a faster solution for my following bash script: (for example some codes in python)
My script load entire *.json in each iteration and takes time.

###
#!/bin/bash
file="Obj_ID_list"      #cityobjects id list
lines=$(cat $file)
for line in $lines
do
	cjio City.json subset --id "$line" export --format obj ./Buildings/$line.obj
done
###

Regards

**Comment by balazsdukai** [comment]
You could pass multiple `--id` to the subset command. Please read the command's documentation on how to do this.

**Comment by Saji70** [comment]
You are correct in the case that I wanna to export all subset IDs in one OBJ file but if I want to export each ID in individual OBJ file, the suggested solution do not work.

**Comment by hugoledoux** [comment]
there is no way to do this with cjio without reloading the model as you did
