### ISSUE TITLE
cjio bounding box 

### ISSUE THREAD

**Issue by Jillinger** [cityjson/cjio#123]
I can't figure out how to use the bounding box. Is there an example somewhere, or can someone show me how?
I tried cjio infile subset --bbox  with several ways to get the minx, miny, maxx, maxy, but get errors. Can I also set the min and max z?

**Comment by Jillinger** [comment]
I found out the answer by [the code here](https://geoforum.nl/t/cityjson-pdok-voor-mij-onhandelbaar-hoe-te-gebruiken/4557/3).
I would delete this thread, but I see no button for that. Perhaps the mods can remove it.

**Comment by hugoledoux** [comment]
I guess it wasn't super clear, so I added usage examples to the help (bbd243c921f8bc5afd9de1446d6c60249a69e539), will be release next week when v0.7 is out.

(issues cannot be deleted, just closed)

**Comment by Jillinger** [comment]
Ah, thanks @hugoledoux.
Will 0.7 allow for a bounding box that clips the z min and max? I thought I might be able to shift some enormously tall buildings below 0, and then clip the bottom, but there is no feature for that, so I am now more than half way through writing  an app in python that takes the height and cuts it down by percentage.

**Comment by hugoledoux** [comment]
This is too specific of an operator to be in cjio in my opinion. We want cjio to be simple and generic.

**Comment by Jillinger** [comment]
Understood.
