### ISSUE TITLE
Support pipes for input and output

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/cjio#137]
**Is your feature request related to a problem? Please describe.**
Add read/write to pipe instead of files. It would help to use cjio in a pipeline with other tools.

**Describe the solution you'd like**
Send the result of the operation chain to the pipe instead of saving them to a file.
Read the cityjson file from the pipe instead of a file.

**Comment by hugoledoux** [comment]
good idea 👍

**Comment by hugoledoux** [comment]
added in v0.7.5
