### ISSUE TITLE
Flipped surfaces after triangulating a city model

### ISSUE THREAD

**Issue by robinjo78** [cityjson/cjio#139]
**Describe the bug**
After using the triangulation function on a tile from the 3D BAG dataset, I found out that some surfaces of some of the buildings in the tile are flipped. It appears as a 'hole' when visualising in Ninja.

**cjio version**
Version 0.7.3

**To Reproduce**
Download this [tile](https://3dbag.nl/en/download?tid=5910).
Then upgrade the CiytJSON file to version 1.1 and triangulate it. The commands are:
`cjio 3dbag_v210908_fd2cee53_5910.json upgrade save 3dbag_5910_v11.city.json`
`cjio 3dbag_5910_v11.city.json triangulate save 3dbag_5910_v11_triangulated.city.json`
Visualise the last cityjson file in Ninja.

**Expected behavior**
Some surfaces of some buildings are expected to be flipped in orientation. This appears as a hole in the building.

**Screenshots**
![image](https://user-images.githubusercontent.com/9788732/167817464-199147d5-86fe-42d4-974a-af34e5676952.png)

**Desktop:**
 - OS: Windows
 - Version: 10

**Comment by hugoledoux** [comment]
1. Which branch did you use?
2. Did you use `triangulate --sloppy`?
3. And are they flipped are simply not present? 
4. Can you isolate it to one building please?

**Comment by robinjo78** [comment]
1. I just used the cjio version I get when I installed it with pip install. It is version 0.7.3., so I guess it is just the main branch.
2. No. See command in the issue.
3. I guess they are flipped. See image: 
![image](https://user-images.githubusercontent.com/9788732/174606758-60c5e391-8cc6-426c-9d57-01c69e2dfc0a.png)
4. See image. I took a subset of the json file by taking the building with the id shown in the image.

**Comment by hugoledoux** [comment]
I cannot reproduce your bug. 

So I isolated one building that goes bad for you in the image you sent, get it there:
https://hugoledoux.stackstorage.com/s/H4wsx4wVYXuZ2nKr 

if you triangulate that one, with and without `--sloppy`, you get errors? 

And ninja does the same?
