### ISSUE TITLE
Level of Details as String

### ISSUE THREAD

**Issue by GANys** [cityjson/cjio#40]
CJIO does not validate files in which LOD are not numbers but strings. Integers and floats are ok.

Accordingly to [this issue](https://github.com/cityjson/specs/issues/52) on the CityJSON Github, it should validate it.

**Comment by balazsdukai** [comment]
The referenced issue doesn't say that cjio is supposed to validate the LoD when it is a string in the file. The issue says that we should change the LoD from a number to a string in the upcoming cityjson specs release.

cjio 0.5.5 follows the current cityjson version 1.0.1, and thus expects that the LoD is a number in the file. The LoD as a string is not valid per current cityjson version.

I'm leaving the issue open as a TODO when the cityjson specs are updated.

**Comment by balazsdukai** [comment]
This was done with v0.7.0 that supports cityjson v1.1
