### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Bas2455** [cityjson/cjio#53]
Hi, I am a Windows 10 user but I don't know how to install cjio. Can someone help me with this?
When I open commandprompt and type: "pip install cjio"  it says: pip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by balazsdukai** [comment]
Hi, cjio need python to run and *pip* is package manager for installing python packages. You error message says that you don't have *pip* installed, which makes me suspect that you don't have python installed or set up correctly.

Please refer to the docs for installing python on Windows at https://wiki.python.org/moin/BeginnersGuide/Download

If you install python on windows with the installers in the link, it installs pip for you automatically. Once done, you can do a `pip install cjio`

**Comment by hugoledoux** [comment]
Python is not in your path in Windows10 (at least wasn't for me), so type this:
```
py -m pip install cjio
```

**Comment by Bas2455** [comment]
Thanks, both for your help! @balazsdukai @hugoledoux
