### ISSUE TITLE
Add reason for invalidity to `validate`

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/cjio#60]
Currently `validate` only prints that the file is invalid and prints the whole cityobject. It would be better to show why is the file invalid. Same is true for warnings.

**Comment by hugoledoux** [comment]
it prints why, it's not very precise but it prints the reason. 

Doing better involves rewriting a JSON-schema validator really, or perhaps it was improved since I did tests and coded this but now it just passes the errors to the console, that's it.

**Comment by balazsdukai** [comment]
The new validator that is integrated into cjio, [cjval](https://github.com/cityjson/cjval) has expressive error messages.
