### ISSUE TITLE
Do not print the whole cityobject to the console in 'validate'

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/cjio#63]
In case of errors, `validate` prints the whole cityobject to the console. If there are many errors, this can quickly become way too much. 
Better to only print the CO ids.

**Comment by Athelena** [comment]
+1 

Just ran a validate with many duplicate and orphan vertices and it was too much.

**Comment by hugoledoux** [comment]
I agree, but it's a bit tricky since I just pass to the console the string that the validator reports... So we would need to parse that one to find the COs.

Doable for sure
