### ISSUE TITLE
Cannot find correct usage parameter for translate

### ISSUE THREAD

**Issue by Itsman-AT** [cityjson/cjio#64]
Dear all,
I am trying to test the translate function in cjio. Could someone point me in the right direction what it is intended to do (maybe I want to do something with it which it cannot) and how the correct syntax looks like? The help text seems to be truncated.
Thanks
Jan

**Comment by balazsdukai** [comment]
Hm, the help text doesn't seem to be truncated for me. But here is the full text. It will translate the input citymodel by the values you pass as parameter.

```
Usage: cjio translate [OPTIONS]

  Translate the file by its (-minx, -miny, -minz).

  Three values can also be given, eg: 'translate --values -100 -25 -1'

Options:
  --values FLOAT...  (x, y, z)
  --help             Show this message and exit.
```

**Comment by Itsman-AT** [comment]
@balazsdukai : Thank you very much. I suppose the x,y and z values are in the units of the projection (SRS) the CityJSON is in?

**Comment by balazsdukai** [comment]
Yes, thats correct. But keep in mind that if you reprojected the citymodel to another srs (with `reproject`) in the same chain, then you would need to pass the values to `translate` in the units of the new srs. For instance `cjio my_model.json reproject 1234 translate ...`
Note that although the help text gives an example with integer values, you can floating point values too. In fact, the values are interpreted as floats.

**Comment by Itsman-AT** [comment]
@balazsdukai: Thanks again. Just as an addendum: This is how my help looks on my screen:
![grafik](https://user-images.githubusercontent.com/41750112/97426206-684ecd80-1913-11eb-8df0-058a0dd9a598.png)

**Comment by balazsdukai** [comment]
Oh I see! That's a feature, not a bug ;-)

In order to see the full help text of a Command, you need to type the command first, then `--help`, otherwise you only get the generic cjio help menu. E.g. `cjio translate --help`

**Comment by Itsman-AT** [comment]
Ah, that was not clear to me :), thanks!
