### ISSUE TITLE
Add test for all CLI commands

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/cjio#73]

**Comment by jliempt** [comment]
This is done with https://github.com/cityjson/cjio/commit/e38912f527d2964c90d7c5747726ffd142ab8742, sufficient enough?

**Comment by balazsdukai** [comment]
@jliempt a few things:

+ Please update the data paths so that it works on other people's machines, both windows and unix ( https://github.com/cityjson/cjio/blob/c03e3988892c03434cbc1bad111b9795dbebe8d9/tests/conftest.py#L131 )

+ Are you sure that this is not possible to solve with vanilla pytest? Adding a new library just for this seems a bit of an overkill to me. https://github.com/cityjson/cjio/blame/develop/tests/test_validate.py#L16

**Comment by jliempt** [comment]
Thanks for checking. There isn't a clean way to do it (as explained in for example https://stackoverflow.com/questions/52764279/pytest-how-to-parametrize-a-test-with-a-list-that-is-returned-from-a-fixture), so I just did it in a verbose manner.

**Comment by balazsdukai** [comment]
Yes I see. Its fine for me, thanks for the corrections. I'm closing this issue, because it has been resolved.
