### ISSUE TITLE
Reproject results in error: AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by marcfsx** [cityjson/cjio#75]
I am using following command:
cjio 19dz1.json reproject 4326 export out_4326.json

the output is:
  File "C:\Python37\Scripts\cjio-script.py", line 11, in <module>
    load_entry_point('cjio==0.6.2', 'console_scripts', 'cjio')()
  File "c:\python37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\python37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\python37\lib\site-packages\click\core.py", line 1290, in invoke
    return _process_result(rv)
  File "c:\python37\lib\site-packages\click\core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "c:\python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\python37\lib\site-packages\cjio\cjio.py", line 103, in process_pipeline
    cm = processor(cm)
  File "c:\python37\lib\site-packages\cjio\cjio.py", line 190, in processor
    if format.lower() == '3dtiles' or not isinstance(cm, list):
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by hugoledoux** [comment]
try `cjio 19dz1.json reproject 4326 save out_4326.json`

save instead of export, which is only if you want to save to another format like glTF

**Comment by marcfsx** [comment]
Hi, Tried the below command. However the repojection resulting in strange result. Here the Original file viewed in QGIS: Here the same file after reprojection using below command: Do I need additional commands, or do I do something wrong ? Cheers, Marc. Van: Hugo LedouxVerzonden: maandag 11 januari 2021 11:03Aan: cityjson/cjioCC: marcfsx; AuthorOnderwerp: Re: [cityjson/cjio] Reproject results in error: AttributeError: 'NoneType' object has no attribute 'lower' (#75) try cjio 19dz1.json reproject 4326 save out_4326.jsonsave instead of export, which is only if you want to save to another format like glTF—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hugoledoux** [comment]
I can't see the results but 4326 is not a 3D CRS, and even if you meant (long, lat, height) then the coordinates in xy would be different from the height (in meters?). This is a recipe for disaster...

**Comment by marcfsx** [comment]
Hi Hugo. Good point.  My goal is to reproject to  EPSG code for the coordinates in latitude and longitude and height above the WGS84 ellipsoid.Searching the net I found these EPSG codes: 7912 or 4979. When I try these with:cjio 19dz1.json reproject 7912 save out_7912.jsonI’ve got this result: Parsing 19dz1.jsonReproject to EPSG:7912Traceback (most recent call last):  File "C:\Python37\Scripts\cjio-script.py", line 11, in <module>    load_entry_point('cjio==0.6.2', 'console_scripts', 'cjio')()  File "c:\python37\lib\site-packages\click\core.py", line 829, in __call__    return self.main(*args, **kwargs)  File "c:\python37\lib\site-packages\click\core.py", line 782, in main    rv = self.invoke(ctx)  File "c:\python37\lib\site-packages\click\core.py", line 1290, in invoke    return _process_result(rv)  File "c:\python37\lib\site-packages\click\core.py", line 1224, in _process_result    value = ctx.invoke(self.result_callback, value, **ctx.params)  File "c:\python37\lib\site-packages\click\core.py", line 610, in invoke    return callback(*args, **kwargs)  File "c:\python37\lib\site-packages\cjio\cjio.py", line 103, in process_pipeline    cm = processor(cm)  File "c:\python37\lib\site-packages\cjio\cjio.py", line 495, in processor    cm.reproject(epsg)  File "c:\python37\lib\site-packages\cjio\cityjson.py", line 1663, in reproject    p2 = pyproj.Proj(init='epsg:%d' % (epsg))  File "c:\python37\lib\site-packages\pyproj\__init__.py", line 362, in __new__    return _proj.Proj.__new__(self, projstring)  File "_proj.pyx", line 129, in _proj.Proj.__cinit__RuntimeError: b"no options found in 'init' file" And:cjio 19dz1.json reproject 4979 save out_4979.jsonSame result: RuntimeError: b"no options found in 'init' file". What am I doing wrong ? Thanks for support, really appreciated,Marc.      Van: Hugo LedouxVerzonden: maandag 11 januari 2021 19:24Aan: cityjson/cjioCC: marcfsx; AuthorOnderwerp: Re: [cityjson/cjio] Reproject results in error: AttributeError: 'NoneType' object has no attribute 'lower' (#75) I can't see the results but 4326 is not a 3D CRS, and even if you meant (long, lat, height) then the coordinates in xy would be different from the height (in meters?). This is a recipe for disaster...—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hugoledoux** [comment]
hmmm, for me it works with a given file with 4979.

Does your input file has a CRS defined? Can you paste the result of `cjio 19dz1.json info` here please.

**Comment by marcfsx** [comment]
It has 7415:

{
  "cityjson_version": "1.0",
  "epsg": 7415,
  "bbox": [
    109970.308000006,
    499971.700001098,
    -4.31099987030029,
    115038.37598706,
    506263.808000978,
    116.769996643066
  ],
  "transform/compressed": true,
  "cityobjects_total": 23824,
  "cityobjects_present": [
    "Building"
  ],
  "materials": false,
  "textures": false
}

**Comment by hugoledoux** [comment]
hmmm, mine had too.

Can you upgrade cjio to latest version perhaps?

**Comment by marcfsx** [comment]
![4979](https://user-images.githubusercontent.com/37207286/111791969-10b1fe00-88c4-11eb-95b1-5dd4e34e7663.JPG)
![7415](https://user-images.githubusercontent.com/37207286/111791972-114a9480-88c4-11eb-9a8f-e89c66f5461c.JPG)
![log](https://user-images.githubusercontent.com/37207286/111791977-11e32b00-88c4-11eb-8901-a784ce3855c4.JPG)
Hi,
upgrading to the latest version of cjio did complete the reprojection (although with warnings).
however the result has distorted the original file.
i've attached these images:
first image: the reprojected result (4979) as viewed in ninja.
second image: the original (7415) as viewed in ninja.
third image: the log i've got with the warnings;

**Comment by hugoledoux** [comment]
you created a file with different coordinates in x-y-z (degree-degree-meter), and most viewer treat all these 3 equally, so it's normal that you have a "distorted" dataset.

and those warning are from the pyproj files, not cjio...
