### ISSUE TITLE
cjio auto-generation of metadata puts the date-time as date

### ISSUE THREAD

**Issue by hugoledoux** [cityjson/cjio#79]
and thus creates schema-invalid files

**Comment by balazsdukai** [comment]
Yup, there is a conflict between https://github.com/cityjson/cjio/blob/0933f655ed3fe75c7c4dd2f0188eceaa9d6349d2/cjio/schemas/1.0.1/metadata.schema.json#L333-L335

and  https://github.com/cityjson/cjio/blob/0933f655ed3fe75c7c4dd2f0188eceaa9d6349d2/cjio/cityjson.py#L1779

Maybe in some other places too.
