### ISSUE TITLE
You always need save command to merge files (other commands?)

### ISSUE THREAD

**Issue by gsclara** [cityjson/cjio#81]
When you try to merge files, you need the save command at the end to write the output. This was somewhat not very clear to me while using the help provided by cjio tool. 

Maybe this applies also to other commands than merge.

**Comment by hugoledoux** [comment]
yes you do, also for other commands.

cjio is not only for transforming the file, you also have "validate" and "info" and others in the future, so automatic saving wouldn't be suitable IMO.

The save option is in the docs and examples, how could we improve this?

**Comment by gsclara** [comment]
I was not thinking about changing the save functionality, but more adding more info to the help command?

**Comment by hugoledoux** [comment]
done for upcoming v0.7 release, cheers
