### ISSUE TITLE
Reproject does not reproject all "geographicalExtent" fields

### ISSUE THREAD

**Issue by jpvirtan** [cityjson/cjio#84]
The command "reproject" does not transform the "geographicalExtent" fields in individual building objects. 
The "geographicalExtent" of the entire model in the metadata does get transformed correctly, as do all the vertices.

**Comment by hugoledoux** [comment]
oh indeed, never thought of this. 

Cheers for reporting!

**Comment by hugoledoux** [comment]
Fixed https://github.com/cityjson/cjio/commit/88459bbdebbc2dd6cec3f94e566423c0b498adee

In branch 'develop', and will be released when CityJSON v1.1 (👀) is released. 

cjio will enforce v1.1 too... in develop there's an update_version() and most of the functions are working. If you want to help us test that would be more than welcome too!
