### ISSUE TITLE
Should a command return with non-zero if an optional module is not available?

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/cjio#88]
On `develop` branch.

Currently if an optional module, eg. pyproj, is not available, cjio doesn't do the operation but still returns with a 0 exit code. The test shows this, as it succeeds even if pyproj is not installed https://github.com/cityjson/cjio/blob/c03e3988892c03434cbc1bad111b9795dbebe8d9/tests/test_cli.py#L280-L293.

As a user I would expect that when I explicitly issue a command, it only returns with a success code when it really succeeded. In fact, I do not want cjio to continue with the next command, unless the previous succeeded. Like that I would get a clear signal that sth failed.

Consider for example `cjio tests/data/rotterdam/rotterdam_subset.json info reproject 4326 info`.

What do you think @hugoledoux ?

**Comment by hugoledoux** [comment]
Fully agree.

We can't return 0 or 1, but block the processor/cm from being passed and `raise click.ClickException('Abort.')`, ok?

Would look like this: https://cln.sh/CRBUwo

**Comment by balazsdukai** [comment]
Yes, I think that's a good solution.

**Comment by hugoledoux** [comment]
fixed in 61d56a24f5b5d26ca8826476a4522d2eec0ace96
