### ISSUE TITLE
Show CityObject hierarchy in `info`

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/cjio#97]
As per @hugoledoux suggestion in #94 , it would be neat if `info()` prints the cityobject hierarchy.

```
|-- Neighbourhood (5)
   |-- Building (412)
      |-- BuildingPart (67)
   |-- TINRelief (1)
```

**Comment by hugoledoux** [comment]
done in ac9921a3e6fd38133474b1b32b331052dd27af0d
